aliases:
  - &restore-gradle-cache
    keys:
      - v1-dependencies-{{ checksum "build.gradle" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

  - &save-gradle-cache
    paths:
      - ~/.gradle
    key: v1-dependencies-{{ checksum "build.gradle" }}

  - &gradle-env
    GRADLE_OPTS: -Dorg.gradle.daemon=false

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: dripstat/internal-java-mckey:latest
      auth:
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASS
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2

jobs:
  build:
    branches:
     only:
      - newbuild
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-gradle-cache
      - run:
         environment: *gradle-env
         command: |
           chmod +x ./gradlew
           ./gradlew build

      - save_cache: *save-gradle-cache

