aliases:
  - &restore-maven-cache
    keys:
        # when lock file changes, use increasingly general patterns to restore cache
        - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
        - maven-repo-v1-{{ .Branch }}-
        - maven-repo-v1-

  - &save-maven-cache
    paths:
      - ~/.m2
    key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: dripstat/internal-java-mckey:maven-3.6.1-1
      auth:
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASS
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2

workflows:
  version: 2

  maven-central-publish:
    jobs:
      - maven-publish:
          filters:
            branches:
              only: master

  compile:
    jobs:
      - compile-only:
          filters:
            branches:
              ignore: master

jobs:
  maven-publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore-maven-cache
      - run:
          command: |
            gpg --batch --import $SIGN_RINGFILE
            mvn --settings maven-settings.xml --batch-mode deploy
      - save_cache: *save-maven-cache

  compile-only:
     <<: *defaults
     steps:
        - checkout
        - restore_cache: *restore-maven-cache
        - run:
           command: |
              mvn --settings maven-settings.xml --batch-mode package
        - save_cache: *save-maven-cache

