defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: dripstat/internal-java-mckey:latest
      auth:
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASS
  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m
    TERM: dumb

version: 2

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
         environment:
           GRADLE_OPTS: -Dorg.gradle.daemon=false

         command: |
           chmod +x ./gradlew
           ./gradlew publishToMavenLocal -Psigning.keyId=$SIGN_KEY_ID -Psigning.password=$SIGN_PASS -Psigning.secretKeyRingFile=$SIGN_RINGFILE

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
